Inline Documentation
casper-ecosystem/casper-client-sdk pull request #169
Opened 2022-07-26 02:30 UTC by dylanireland

Inline, TypeDoc compliant documentation written for the following files

[CasperServiceByJsonRPC.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/services/CasperServiceByJsonRPC.ts)
[CasperClient.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/CasperClient.ts)
[Contracts.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/Contracts.ts)
[DeployUtil.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/DeployUtil.ts)
[ByteConverters.ts](https://github.com/casper-ecosystem/casper-js-sdk/blob/inline-documentation/src/lib/ByteConverters.ts)

2022-08-05 13:13 UTC, hoffmannjan requested changes
Awesome job @dylanireland , only few small issues that needs to be addressed. Cheers!

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/CasperClient.ts
> +   * @param algo The signature algorithm of the account. Currently we support Ed25519 and Secp256K1
maybe we can add the info that possible values are `SignatureAlgorithm.Ed25519` and `SignatureAlgorithm.Secp256K1`, what do you think?

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/CasperClient.ts
> +   * @returns New key pair with the specified SignatureAlgorithm
same as above

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/CasperClient.ts
> +   * @returns A deployable Deploy object
In fact its not `deployable` as it's not signed ;)

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/CasperClient.ts
> +   * @returns The sent Deploy's transaction hash, as a string
hex representation of transaction hash :)

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/Contracts.ts
> +   */
you can add that `contractPackageHash` is an optional parameter and is only used when there is some event processing

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/Contracts.ts
> +   */
really good, in future this method will be alias to some different method `callModuleBytesEntrypoint` :)

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/Contracts.ts
> +   * @param entryPoint The entrypoint of a smart contract that you wish to call
the name of an entrypoint in fact

2022-08-05 13:13 UTC, hoffmannjan commented on src/lib/Contracts.ts
> +   * @param chainName The name of the network the installment deploy will be sent to. Use "casper" for the Casper mainnet, "casper-test" for the Casper official testnet, and "casper-net-*" for local
this is true (currently) but I'm not sure if this should be part of the inline docs, as when the network names will change someday we will need to remember about this place in docs :). maybe its better to say that you can always check the network name by calling REST endpoint of a node, eg `:8888/status` and get the network name :)

2022-08-10 14:14 UTC, dylanireland commented on src/lib/CasperClient.ts
> +   * @returns New key pair with the specified SignatureAlgorithm
Needs updating

2022-08-16 14:19 UTC, hoffmannjan approved these changes

2022-08-19 14:20 UTC, merged